# Generated by Django 3.2.13 on 2022-05-18 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="us_id",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
