# Generated by Django 3.2.13 on 2022-05-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('limit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('data', models.CharField(max_length=200)),
                ('hw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework')),
            ],
        ),
    ]
