# Generated by Django 3.2.13 on 2022-05-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_submition_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submition',
            name='data',
            field=models.TextField(max_length=1500, unique=True),
        ),
    ]
